modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "aaa_particles_world"
version = "${version}"
displayName = "AAAParticles: World"
authors = "ChloePrime"
description = "The lightning is back!"
logoFile = "assets/aaa_particles_world/icon.png"

[[dependencies.aaa_particles_world]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aaa_particles_world]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aaa_particles_world]]
modId = "architectury"
type = "required"
versionRange = "[13.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.aaa_particles_world]]
modId = "aaa_particles"
type = "required"
versionRange = "[1.21,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "aaa_particles_world.mixins.json"
